fixes resolve issues and adds missing dependency
When consuming ecl-webcomponents-vue in vitepress, the vitepress build process fails due to file resove issues. Error was:

  vitepress v2.0.0-alpha.17

✓ building client + server bundles...
build error:
Cannot find module '/vitepress-ecl-webcomponents/node_modules/@ecl/ecl-webcomponents-vue/dist/components' imported from /vitepress-ecl-webcomponents/node_modules/@ecl/ecl-webcomponents-vue/dist/index.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vitepress-ecl-webcomponents/node_modules/@ecl/ecl-webcomponents-vue/dist/components' imported from /vitepress-ecl-webcomponents/node_modules/@ecl/ecl-webcomponents-vue/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49)

These changes improve the package.json and fixes a missing dependency, so that lookup works again